#! /usr/bin/env python3

from lexer import Lexer
import argparse

def main():
    parser = argparse.ArgumentParser(description="Parse JSON")
    
    parser.add_argument('file', help="JSON file to parse")
    
    args = parser.parse_args()
    
    text = ""
    with open(args.file, 'r') as file:
        text = file.read()
    print("text in the file: ", text, "\n\n")
    lexer = Lexer(text)
    
    lexer.process_file()
    
    
if __name__ == "__main__":
    main()